name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Build Vite App
        run: |
          npm install
          npm run build

      - name: Copy file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/vite-app"

      - name: SSh into EC2 and run app on port 30082
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd "/home/ubuntu/vite-app"
            npm install
            pm2 delete vite-app || true
            pm2 start npm --name vite-app -- run preview -- --host 0.0.0.0 --port 30082
            pm2 save